
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.0"
inhibit_all_warnings!

target 'JEKit 1.1' do

pod 'YYKit'
pod 'FMDB'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJRefresh'

end
