source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.2"
inhibit_all_warnings!

target 'JEKit' do

pod 'YYKit'
pod 'FMDB'
pod 'Masonry'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJRefresh'
pod 'SDWebImage'

end
